### ISSUE TITLE
Facebook...

### ISSUE THREAD

**Issue by notDavid** [jmdugan/blocklists#12]
Wouldn't it be a better method to create a facebook block list with something like:
```
whois -h whois.radb.net '!gAS32934' | tr ' ' ', '
```
as described here? : https://www.perpetual-beta.org/weblog/blocking-facebook-on-os-x.html

**Comment by T3stX** [comment]
That method, find IP addresses, the list of blocklist work with domain names.
Could be possible to reverse lookup IPs but 60.000....

**Comment by notDavid** [comment]
ahhhh right. My bad, it thought it would also be possible to do this in the host file:
```
0.0.0.0 204.15.20.1
0.0.0.0 204.15.20.2
```
etc.

but that doesn't work :/
