### ISSUE TITLE
great facebook blocklist but about instagram

### ISSUE THREAD

**Issue by survivor303** [jmdugan/blocklists#21]
what i need to remove that i get instagram working? (i already removed all instagram related hosts but there is still some)

and if you know direct ip addresses for instagram services, please list them, so people can use that list to allow trafic to them. :)

thanks.

**Comment by LOQUILLO** [comment]
Hi @survivor303 I can help you if you paste here the host file

**Comment by gaia** [comment]
manually add all the lists below, except instagram:

https://i.imgur.com/dgo0f64.png
