### ISSUE TITLE
additional facebook domains

### ISSUE THREAD

**Issue by gravityfuel** [jmdugan/blocklists#34]
0.0.0.0 bg-bg.facebook.com
0.0.0.0 bn-in.facebook.com
0.0.0.0 bs-ba.facebook.com
0.0.0.0 business.facebook.com
0.0.0.0 ca-es.facebook.com
0.0.0.0 da-dk.facebook.com
0.0.0.0 developers.facebook.com
0.0.0.0 el-gr.facebook.com
0.0.0.0 error.facebook.com
0.0.0.0 es-es.facebook.com
0.0.0.0 es-la.facebook.com
0.0.0.0 fa-ir.facebook.com
0.0.0.0 fburl.com
0.0.0.0 fi-fi.facebook.com
0.0.0.0 fr-ca.facebook.com
0.0.0.0 fr-fr.facebook.com
0.0.0.0 graph.facebook.com
0.0.0.0 gu-in.facebook.com
0.0.0.0 hi-in.facebook.com
0.0.0.0 hr-hr.facebook.com
0.0.0.0 id-id.facebook.com
0.0.0.0 streaming-graph.facebook.com
0.0.0.0 ta-in.facebook.com
0.0.0.0 te-in.facebook.com
0.0.0.0 th-th.facebook.com
0.0.0.0 upload.facebook.com
0.0.0.0 ur-pk.facebook.com
0.0.0.0 vi-vn.facebook.com
0.0.0.0 secure.facebook.com
0.0.0.0 scontent-bom1-1.xx.fbcdn.net
0.0.0.0 scontent.xx.fbcdn.net
0.0.0.0 our.intern.facebook.com
0.0.0.0 pa-in.facebook.com
0.0.0.0 phabricator.intern.facebook.com

**Comment by sdxkjsdbnbgvbhsenjjnd** [comment]
0.0.0.0 scontent-syd2-1.xx.fbcdn.net

**Comment by jmdugan** [comment]
thank you - please create pull request, will add them.  /J

**Comment by drduh** [comment]
Please send a Pull Request if these are still missing. Thanks!
