### ISSUE TITLE
[Info] FB blocking hosts file added to hosts.extras repo

### ISSUE THREAD

**Issue by FadeMind** [jmdugan/blocklists#39]
Hi @jmdugan , I added your great job hosts file with facebook and other domains blocking to https://github.com/FadeMind/hosts.extras via commit  https://github.com/FadeMind/hosts.extras/commit/a7ae9f69500e59b43951877bac7b46a74574273f

Regards, FadeMind

**Thanks for your work!**

CC @stevenblack

**Comment by drduh** [comment]
:+1:
