### ISSUE TITLE
what about messenger.com in the facebook blocklist?

### ISSUE THREAD

**Issue by siFeiden** [jmdugan/blocklists#4]

**Comment by jmdugan** [comment]
yup, missed.  belongs in file "all" for sure, and probably one of the smaller, more specific files.  if there are several different servers to maintain for the service, probably merits it's own file as corporations/facebook/messenger

the file structure of how that works is still tbd, but use cases supporting more specific "use-related" blocking would be possible if sub-companies and sub-uses are broken down for such large companies.

**Comment by drduh** [comment]
It's there now, let us know if any domains were missed.
