### ISSUE TITLE
Editing /etc/hosts on macOS

### ISSUE THREAD

**Issue by jidicula** [jmdugan/blocklists#40]
I appended the contents of this file to my /etc/hosts file. The behaviour changed as expected after flushing the DNS cache, but upon rebooting the behaviour reverted back to unblocked facebook domains. However, the /etc/hosts file still contains the changes. Does anyone have any suggestions on how to approach this?

https://github.com/jmdugan/blocklists/blob/0c08bd09c30a7d0082ef6cb881fcf5127a1fc37d/corporations/facebook/all#L6

**Comment by berdot** [comment]
I have the same issue.

**Comment by drduh** [comment]
Not a problem with the blocklists, closing out.
