### ISSUE TITLE
Blocking FB except React.js developer tools & SDKs?

### ISSUE THREAD

**Issue by nwhitmont** [jmdugan/blocklists#43]
First of all, thanks for providing these great lists.   Of primary interest is the FB block list. 

One thing I ran into after adding the complete FB block list to my /etc/hosts file, I'm unable to use React developer tools or download the SDK bundle from `https://connect.facebook.net/en_US/sdk.js`. 

I'm looking for anyone who has run into this same issue and has tips or thoughts. 

Is it enough to whitelist the SDK bundle URL listed above? Or are there other parts of React.js framework that need to connect to other FB URLs?

Disclaimer: I'm not trying to use the FB website, just as a developer working with React.js framework at work.

Thanks in advance for any insight into this issue.

**Comment by drduh** [comment]
You'll probably want to ask Facebook developers about this.
