### ISSUE TITLE
Facebook Zero and related subdomains?

### ISSUE THREAD

**Issue by kowith337** [jmdugan/blocklists#49]
1. I want to just only block subdomains that related to **Facebook Zero** (aka. Free Basics, internet.org, Ø)
2. I've realise I got weird connections than usual (I mean different between normal network such as home Wi-Fi and mobile network)
3. I knew that blocking some related domains will lead to broken usability and/or functionality to use Facebook, especially on mobile browser (I won't use their official apps anymore), I've wrote [some example and details](https://github.com/kowith337/PersonalFilterListCollection/tree/master/docs/Facebook0-Bypassing.md) about what the hell happen if you're using Facebook on mobile data, especially if the mobile carrier have **Free Basics** services available, no matter that you've registered for it or not.

**Comment by drduh** [comment]
Feel free to send a Pull Request for only Facebook Zero domains. Thanks.
