### ISSUE TITLE
a few thousand more Facebooks

### ISSUE THREAD

**Issue by jawz101** [jmdugan/blocklists#55]
[facebooks.txt](https://github.com/jmdugan/blocklists/files/3040218/facebooks.txt)

Every day Cisco Umbrella/OpenDNS releases the top 1 million DNS queries they receive.  Shuffling through the list finds a big chunk of additional subdomains based on real-world traffic.

http://s3-us-west-1.amazonaws.com/umbrella-static/index.html

**Comment by fat-tire** [comment]
This is good.  I was gonna suggest portal.facebook.com and sure enough it's up there.

**Comment by drduh** [comment]
Take a look at the updated Facebook lists and please send a Pull Request with any additional domains we're missing. Thanks.
