### ISSUE TITLE
Facebook developer page

### ISSUE THREAD

**Issue by denterwiser** [jmdugan/blocklists#56]
https://developers.facebook.com/docs/apps/test-pages/?_fb_noscript=1

I have your list in my hosts file and it works great, but I can still reach this page! I'm not a coder, so I don't know what to do to figure this out. Please help.

Thank you

**Comment by jmdugan** [comment]
to fix, you can add this line to your hosts file:
0.0.0.0 developers.facebook.com

or, re-load and add the raw corporations->facebook->all file from git into your hosts file, it's been fixed there too by adding that line.

/J
