### ISSUE TITLE
project maintenance

### ISSUE THREAD

**Issue by jmdugan** [jmdugan/blocklists#57]
I've had very limited time and attention to devote to basic maintenance, issue handling, etc

some issues are now  year+ old and require 10-20 minutes a month on a regular basis to update and reply to things.

Please reply in thread if you've like to be added to the project to help,

Thank you!

Jonathan

**Comment by drduh** [comment]
I can give you a hand with it.

**Comment by jmdugan** [comment]
invited

**Comment by drduh** [comment]
Not seeing it show up, mind trying again?

**Comment by jmdugan** [comment]
deleted and resent

**Comment by drduh** [comment]
Thanks, it was ending up in my Spam folder :woman_shrugging:
