### ISSUE TITLE
more pinterest (some crawlers, some new domains) for you

### ISSUE THREAD

**Issue by eladkarako** [jmdugan/blocklists#65]
[old.txt](https://github.com/jmdugan/blocklists/files/4496717/old.txt)

[new.txt](https://github.com/jmdugan/blocklists/files/4496718/new.txt)

![2020-04-18_165521](https://user-images.githubusercontent.com/415238/79639545-2b9c5f80-8195-11ea-89d9-932dee8af55c.jpg)

<hr/>

for https://github.com/jmdugan/blocklists/tree/master/corporations/pinterest .

I've used https://github.com/eladkarako/SubDomains-with-VirusTotal-and-SecurityTrails-API 
which query virustotal for subdomains + domain siblings. 

and https://github.com/eladkarako/sortjs (nodejs) with 'sort__extraction_rule__url_upsidedown_domain_order.cmd' to make it easily compare your list and new one.

note 'www.' prefix can be added to anything, I've removed it since my own HOSTS generator https://github.com/eladkarako/hosts/blob/master/_builder.js#L98-L121 (nodejs) does a good job adding it automatically.

**Comment by drduh** [comment]
Please submit a Pull Request with the changes you'd like.
