### ISSUE TITLE
additional 'Facebook except WhatsApp'

### ISSUE THREAD

**Issue by eladkarako** [jmdugan/blocklists#66]
I've removed just the ones that have 'whats' appears in the domain name. 

[all_facebook__except_for_domains_with_whatsapp_in_their_name.txt](https://github.com/jmdugan/blocklists/files/4496766/all_facebook__except_for_domains_with_whatsapp_in_their_name.txt)

working same way as in https://github.com/jmdugan/blocklists/issues/65 
I've also removed www. prefix domains since those can be added to every line anyway.

**Comment by drduh** [comment]
Send it our way with a Pull Request, please.
