### ISSUE TITLE
Enhancement.

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [jmdugan/blocklists#70]
It was suggested to me over at GitLab that I pull in missing hosts for my new ZuckerBlock hosts-file. It includes Giphy hosts, as well as Oculus & Libra, and is `CC0`. So have a look, pull in what you need, and I'll do the same as we are both using the `CC0` license. The repo is here: https://gitlab.com/intr0/zuckerblock. Peace.

**Comment by beerisgood** [comment]
Gitlab have smaller community so i don't know which improvements this will give you.

**Comment by elvey** [comment]
I want to be able to quickly delete all fb-related cookies, etc from my browser, so I'm looking for a list of expressions to search the cookie list to delete.  I can sort of eyeball a corporations/Facebook/all or ZuckerBlock list, looking at the second level part of the domains (SLD) and do it that way.  Anyone else interested in such a list?  (Facebook, insta, fbc...?   ).   As long as this Issue has a vague title, this seems like a not awful place to mention this enhancement idea - and get feedback.  Thinking selecting out the SLDs plus `| sort | uniq` would be an OK way to generate it, but maybe not.

**Comment by drduh** [comment]
Send PRs.
