### ISSUE TITLE
Collaboration with someonewhocares.org

### ISSUE THREAD

**Issue by echernyavskiy** [jmdugan/blocklists#8]
Have you considered collaborating with http://someonewhocares.org/hosts/? They've got 12K+ /etc/hosts entries.

**Comment by jmdugan** [comment]
yes!  would love to.  at this point they have a huge list, very well maintained.  this project is a few days old, without a community of users, submitters or maintainers yet.  we don't have much to offer them in a collaboration.  so for now, we've just pointed users to them, see 
https://github.com/jmdugan/blocklists/blob/master/ad_servers/README.md

the one area we may build up are corporate lists that could be useful.  comprehensive lists may not work well for large corps, though.  it looks like 260K ip addresses for facebook, as one example.

**Comment by tbds** [comment]
See [FreeContributor - Contribution](https://github.com/tbds/FreeContributor/blob/master/CONTRIBUTING.md)

**Comment by MattiSG** [comment]
For those interested, I wrote a wrapper script around downloading, enabling and disabling someonewhocares.org hosts file: https://github.com/MattiSG/adblock. The same logic could probably be used with this source.

**Comment by jmdugan** [comment]
thank you!

**Comment by drduh** [comment]
Resolving due to inactivity. Reopen if you think this is still important.
