### ISSUE TITLE
Need blocklist for Nestlé

### ISSUE THREAD

**Issue by seanpm2001** [jmdugan/blocklists#80]
I was citing sources earlier today and I have noticed that Nestlé is doing a massive amount of search engine manipulation, even on DuckDuckGo. There were many different domains and it made it really hard to find any criticism about them. I am not sure if Nestlé is using trackers, or if a blocklist is necessary for this project, but they have hundreds of different domains they are using to try and suppress their criticism. Out of 7 different searches and over 60 pages of results, I was only able to find 16 pages not by them. Judging by this, it seems a bit sketchy. Would a Nestlé blocklist suit this project?

**Comment by drduh** [comment]
Please reopen if this is still an issue, with specific examples and domains which are potentially worth blocking.
