### ISSUE TITLE
Stalkerware Domains?

### ISSUE THREAD

**Issue by robbie-next** [jmdugan/blocklists#84]
I'm am so sorry if I'm not supposed to ask this here, similar queries are not uncommon in git repos & it's definitely relevant to your work, so I'm hoping I'm not being rude or bothersome, but...

Is there any hope of building a blocklist for domains that facilitate stalkerware (like Flexispy, mSpy, AutoForward Spy, etc)? And are they using CDNs like Cloudflare for distribution & delivery or worse...leveraging TLS & other security solutions, like Google's gstatic, gvt1, gvt2...to hide their traffic?

**Comment by drduh** [comment]
Check https://www.netify.ai/resources/applications and the HTTPS Everywhere Atlas to see if the domain names are known, and send a PR if you're still interested.
