### ISSUE TITLE
FreeContributor is 404 and Brave Search doesn't find it

### ISSUE THREAD

**Issue by GETandSELECT** [jmdugan/blocklists#90]
Hi

from README.md

> Yes. If you want that solution, see [dnsmasq](http://www.thekelleys.org.uk/dnsmasq/doc.html) and projects like these: [FreeContributor](https://github.com/evilneuro/FreeContributor).

The FreeContributor link is 404 and a Brave Search doesn't find it https://search.brave.com/search?q=FreeContributor.

Wiped from Internet?

Any alternative?

**Comment by snowcatridge10** [comment]
https://web.archive.org/web/20201202012548/https://github.com/evilneuro/FreeContributor
