### ISSUE TITLE
Threads domains

### ISSUE THREAD

**Issue by b9AcE** [jmdugan/blocklists#95]
There should be an addition of the domains for Threads by Meta Platforms (formerly Facebook, Inc) in these https://github.com/jmdugan/blocklists/tree/master/corporations/facebook lists.

**Comment by drduh** [comment]
Do you know of any other than `threads.net`?

**Comment by b9AcE** [comment]
> Do you know of any other than `threads.net`?
Sorry, no, I was hoping to acquire that information through this project actually, guessing that someone involved in it had already set up some methodology for extracting domains associated with organizations through e.g. the WHOIS-database and/or DNS or such.

**Comment by drduh** [comment]
Reopen with additional domain names if you would like to add them to the list.
